### ISSUE TITLE
[BUG]Record on stages when you fall

### ISSUE THREAD

**Issue by edyedyy** [surftimer/Surftimer-Official#270]
Like you see in this video : https://youtu.be/QMDZWp0x-sU

**Comment by Kyli3Boi** [comment]
This is not a bug but poor zoning that causes this

**Comment by edyedyy** [comment]
What do you mean with "poor zoning" >> zone example https://imgur.com/dqoXxM7

> This is not a bug but poor zoning that causes this

**Comment by Kyli3Boi** [comment]
show your end zone

**Comment by edyedyy** [comment]
Here is the endzone : https://imgur.com/2VhDIwL
I use now **Release 285** and I want to upgrade.

**Comment by Kyli3Boi** [comment]
Okay im not sure then as i know this happens with bonus zones but have never seen it on normal zones to be honest.

285 is the stable version and would not recommend upgrading as there are many known bugs but there is no one actively working on resolving them.

**Comment by olokos** [comment]
@edyedyy 
Try to use the zones from the sql in the repo, they worked since always AFAIK for surf_beginner, especially on 285

As @Kyli3Boi said, currently 285 is considered stable, if you want to upgrade I recommend doing proper backups of your db's in case you want to roll back.
Performance-wise dev is better than 285, from my experience, but there are some issues we still need to solve before its stable, such as not displaying proper rank clantags, among other things.

I'm currently quite busy with University, end of semester and another year, so it's quite intense.

**Comment by edyedyy** [comment]
> @edyedyy
> Try to use the zones from the sql in the repo, they worked since always AFAIK for surf_beginner, especially on 285
> 
> As @Kyli3Boi said, currently 285 is considered stable, if you want to upgrade I recommend doing proper backups of your db's in case you want to roll back.
> Performance-wise dev is better than 285, from my experience, but there are some issues we still need to solve before its stable, such as not displaying proper rank clantags, among other things.
> 
> I'm currently quite busy with University, end of semester and another year, so it's quite intense.

Thank you for the reply! I will try!
