### ISSUE TITLE
[BUG] Exception reported: Array index out-of-bounds (index -1, limit 128)

### ISSUE THREAD

**Issue by freakexeuLow** [surftimer/Surftimer-Official#350]
**Describe the bug**
Before this topic goes down, I wanted to post it on Github. When exactly the problem comes I can't say, but I have recent logs of it that have over 300+ mb and hope that someday someone nice and social might fix this problem.

```
L 11/03/2021 - 00:00:00: SourceMod error session started
L 11/03/2021 - 00:00:00: Info (map "surf_paradigm") (file "/server/csgo/csgo/addons/sourcemod/logs/errors_20211103.log")
L 11/03/2021 - 00:00:00: [SM] Exception reported: Array index out-of-bounds (index -1, limit 128)
L 11/03/2021 - 00:00:00: [SM] Blaming: SurfTimer.smx
L 11/03/2021 - 00:00:00: [SM] Call stack trace:
L 11/03/2021 - 00:00:00: [SM]   [1] Line 902, surftimer/hooks.sp::OnPlayerRunCmd
L 11/03/2021 - 00:00:00: [SM] Exception reported: Array index out-of-bounds (index -1, limit 128)
```

**Expected behavior**
That the SurfTimer plugin does not spam the server with many logs :P

**Plugin List**
SurfTimer -->Master<-- Version

**Comment by 1zc** [comment]
> hope that someday someone nice and social might fix this problem.

cringe. Anyways...

Zone ID gets set to -1 if the clients not in any zone, so I'm not entirely sure why this happens when a client crosses a max speed zone. I tried doing a bit of testing, and the only thing I can really think of is maybe g_iClientInZone[client][3] is being set to something valid a bit delayed and hence causing the spam of errors before that happens? 

Unsure about this, would love some more opinions if anyone is interested in looking into it deeper - for now, I don't see any harm in adding a check to ensure the index is above `-1` before limiting max speed, so I'll pull request that in a bit to prevent the massive spam of error logs.
